namespace Cipheroom.Domain.Rooms;

/// <param name="Name">Media server track name, generated by the server (<see cref="NameFor"/>) so clients can't
/// claim or overwrite someone else's tracks. Never sent to clients.</param>
/// <param name="Mid">The publisher's transceiver mid for this track on its own media session.</param>
public sealed record PublishedTrack(string Name, TrackSource Source, string Mid, bool Muted = false)
{
    public TrackKind Kind => Source.Kind();

    public static string NameFor(ParticipantId owner, TrackSource source) => $"{owner.Value}-{source.ToWire()}";
}

/// <summary>A remote track a participant receives, under the receiving transceiver's <paramref name="Mid"/>.</summary>
public sealed record Subscription(string Mid, ParticipantId PublisherId, TrackSource Source);
